### ISSUE TITLE
Chapter 6

### ISSUE THREAD

**Issue by Sant-projects** [PacktPublishing/Server-Side-Development-with-Node.js-and-Koa.js-Quick-Start-Guide#1]
Hi,
 when trying to run the Chapter 6 code:
 1) Auth is working.
 2)Post section, I am not able to create posts using http://localhost:3000/post/create .

I started with an empty database with you chapter 6 code, created user, then not able to create posts using http://localhost:3000/post/create .

 I tried both codes from GitHub and packt.

**Comment by olayinkaos** [comment]
Hi @Sant-projects,

Thanks for spotting this. In the code files, the 'create' route should be registered before the route to show each post. If the 'show' route is registered before, the app will attempt to fetch a post with the id `create` from the database and display it.

This has been fixed in the [latest commit](https://github.com/PacktPublishing/Server-Side-Development-with-Node.js-and-Koa.js-Quick-Start-Guide/commit/cc74fd283ee015bce3e3ab0553de7fa52134f9f8). You can pull again and let me know if it works fine.
Cheers.

**Comment by Sant-projects** [comment]
Hi @olayinkaos,

After debugging, found out the routing order was the issue. 
Later adjusting the "show" routing position it worked.

FYI, One more errata is on page 66 (pdf) (Creating data models):
     the code shown is index.js
      should be Contact.js

Regards,
Sant

**Comment by olayinkaos** [comment]
Hi, @Sant-projects.

Yes, this has been spotted. Thank you for reading and taking the time to send feedback.
I'll close this issue for now. Feel free to send any more feedback/errata/issues.

Cheers.
